package fu.de200357.account;

public enum ResultCode {
    SUCCESS,
    INVALID_INPUT,
    INVALID_USERNAME,
    INVALID_EMAIL,
    WEAK_PASSWORD,
    PASSWORD_MISMATCH,
    UNDERAGE,
    INVALID_PHONE,
    DUPLICATE_USERNAME,
    DUPLICATE_EMAIL,
    INVALID_CREDENTIALS,
    ACCOUNT_DISABLED,
    ACCOUNT_LOCKED,
    USER_NOT_FOUND
}
